name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'infra/**'
      - 'shared/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install share dependencies
        run: |
          cd shared
          npm install

      - name: Build shared
        run: |
          cd shared
          npm run build

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install infra dependencies
        run: |
          cd infra
          npm install

      - name: Build backend
        run: |
          cd backend
          npm run build

      - name: Synthesize CDK
        run: |
          cd infra
          npx cdk synth

      - name: Configure AWS Credentials for Milan region audience
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: eu-south-1
          role-to-assume: arn:aws:iam::874456855336:role/github_actions_deploy

      - name: Get caller identity
        run: |
          aws sts get-caller-identity

      - name: Deploy CDK stack
        run: |
          cd infra
          npx cdk deploy --all --require-approval never
