name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'
      - 'infra/**'
      - 'shared/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install share dependencies
        run: |
          cd shared
          npm install

      - name: Build shared
        run: |
          cd shared
          npm run build

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install infra dependencies
        run: |
          cd infra
          npm install

      - name: Build backend
        run: |
          cd backend
          npm run build

      - name: Synthesize CDK
        run: |
          cd infra
          npx cdk synth
